### PR TITLE
Make use of FunctionGaugeSupport if possible

### PR DESCRIPTION
**Pull request by jmartisk**
Second part of the fix needed for https://github.com/quarkusio/quarkus/issues/12196

### CODE REVIEW

**Review by Ladicek — APPROVED** [review]

**Comment by Ladicek** [comment]
I guess you need a release with this change?

**Comment by jmartisk** [comment]
@Ladicek yes please! I would do that myself but wasn't entirely sure that you don't want to include anything else in it

**Comment by Ladicek** [comment]
No, `master` is always releasable :-) I'll get the ball rolling.

**Comment by Ladicek** [comment]
Well actually I _do_ want to add one more thing (deprecate a few bits of the experimental API). I'll get it in, and the release should be later today.

**Comment by jmartisk** [comment]
Perfect, thanks!

**Comment by Ladicek** [comment]
4.3.1 release is now done and should be available in Central soon.

**Comment by Ladicek** [comment]
Aaaand 4.3.1 is in Central: https://repo.maven.apache.org/maven2/io/smallrye/smallrye-fault-tolerance/4.3.1/

**Pull request merged**
