### PR TITLE
add ability to disable individual metric providers

### LINKED ISSUE #1078: Exposing MP Config properties for individually disabling metrics providers
Following up on fixing CompoundMetricsProvider https://github.com/smallrye/smallrye-fault-tolerance/issues/1072, I am starting to think that we need to expose MP Config properties for cases when multiple metrics providers are discovered (either by mechanism built-in to SR FT or by the mechanism that WF uses) to handle scenarios when in a single deployment, users elect to use MP Telemetry for tracing, yet want to e.g. continue using Micrometer for MP FT metrics collection. While Telemetry has specific properties for disabling, it would disable for the whole deployment. MP FT has properties for only disabling metrics altogether. While the MP FT spec is alright with collecting metrics with multiple providers simultaneously (which is beneficial for gradual migration or monitoring systems compatibility), there are drawbacks such as performance implications, potentially duplicated metrics if feeding into the same metric. Thoughts?

### PR DESCRIPTION
**Pull request by Ladicek**
Resolves #1078

### CODE REVIEW

**Comment by rhusar** [comment]
Let me take this for a quick spin.

**Comment by Ladicek** [comment]
Please report back; I'll keep this open until then.

**Review by rhusar — APPROVED** [review]
I tried a few things and this seems to worked exactly as I wanted to. Last piece of the OpenTelemetry puzzle is in place!

Also reviewed the code and LGTM.

**Comment by rhusar** [comment]
As discussed, will be backported to 6.6.x.

**Comment by Ladicek** [comment]
The PR https://github.com/smallrye/smallrye-fault-tolerance/pull/1080 backports this to 6.6. I'll release 6.6.3 later today.

**Pull request merged**
