### PR TITLE
update SmallRye Parent and move to Jakarta dependencies

### LINKED ISSUE #157: move from Java EE artifacts to Jakarta EE artifacts
https://github.com/orgs/smallrye/projects/2#card-30494938

This most likely needs to happen both in 2.x and 4.x.

### PR DESCRIPTION
**Pull request by Ladicek**
Resolves #157.

### CODE REVIEW

**Comment by Ladicek** [comment]
Hi @rhusar, would this be OK/not OK/don't care for you, from WildFly perspective?

**Comment by Ladicek** [comment]
Gonna merge anyway :-)

**Comment by rhusar** [comment]
@Ladicek Back from PTO today. Looking.

**Comment by rhusar** [comment]
@Ladicek So my understanding is that this OK for us from WildFly perspective (though not 100% sure about backports to older versions of e.g. EAP but as long its still using old package names in the code, that should be fine).

**Comment by Ladicek** [comment]
Cool, thanks!

**Pull request merged**
