### PR TITLE
debug logging to figure out why the test is failing on a slow machine

### PR DESCRIPTION
**Pull request by Ladicek**
This is NOT supposed to be merged, I just want to figure out why the test sometimes fail on CI. I don't know how to get it failing locally.

### CODE REVIEW

**Comment by rhusar** [comment]
@Ladicek btw you can use draft PR GH feature if you don't want the PR to be mergeable https://github.blog/2019-02-14-introducing-draft-pull-requests/

**Comment by Ladicek** [comment]
I know about draft PRs, but I think Semaphore doesn't run in such case. Well, I should have tried. Next time :-)

**Comment by rhusar** [comment]
ah yeah, its possible the CI integration code has not yet been updated to also test draft PRs... we have the same problem with WildFly CI.

**Comment by Ladicek** [comment]
Here's a trace from a failing execution (see also https://semaphoreci.com/smallrye/smallrye-fault-tolerance/branches/pull-request-212/builds/10):

```
2020-04-01 10:03:02.028 [main] invoking CompletionStageFallback
2020-04-01 10:03:02.028 [main] invoking CompletionStageRetry
*************************** main retry attempt 0
2020-04-01 10:03:02.028 [main] invoking CompletionStageTimeout
2020-04-01 10:03:02.031 [main] finished CompletionStageTimeout
2020-04-01 10:03:02.031 [main] finished CompletionStageRetry
^^^^^^^^^^^^^^^^^^^^^^^^^^^ pool-1-thread-64 running guarded method
!!!!!!!!!!!!!!!!!! pool-1-thread-64 finished {traceId:79, spanId:81, parentId:80, operationName:"hello"}
%%%%%%%%%%%%%%%%%%%%%%%%%%% pool-1-thread-64 failed without timeout
2020-04-01 10:03:02.031 [main] finished CompletionStageFallback
*************************** pool-1-thread-64 retry attempt 1
2020-04-01 10:03:02.134 [pool-1-thread-64] invoking CompletionStageTimeout
2020-04-01 10:03:02.135 [pool-1-thread-64] finished CompletionStageTimeout
^^^^^^^^^^^^^^^^^^^^^^^^^^^ pool-1-thread-65 running guarded method
!!!!!!!!!!!!!!!!!! pool-1-thread-65 finished {traceId:79, spanId:82, parentId:80, operationName:"hello"}
%%%%%%%%%%%%%%%%%%%%%%%%%%% pool-1-thread-65 failed without timeout
*************************** pool-1-thread-65 retry attempt 2
2020-04-01 10:03:02.226 [pool-1-thread-65] invoking CompletionStageTimeout
%%%%%%%%%%%%%%%%%%%%%%%%%%% pool-2-thread-3 timeout from watcher thread
%%%%%%%%%%%%%%%%%%%%%%%%%%% pool-1-thread-66 timeout completing on original executor
2020-04-01 10:03:02.231 [pool-1-thread-65] finished CompletionStageTimeout
*************************** pool-1-thread-65 retry attempt 3
$$$$$$$$$$$$$$$$$$$$$$$$$$$ pool-1-thread-65 fallback logic
!!!!!!!!!!!!!!!!!! pool-1-thread-65 finished {traceId:79, spanId:83, parentId:80, operationName:"fallback"}
^^^^^^^^^^^^^^^^^^^^^^^^^^^ pool-1-thread-67 running guarded method
!!!!!!!!!!!!!!!!!! pool-1-thread-67 finished {traceId:79, spanId:84, parentId:80, operationName:"hello"}
!!!!!!!!!!!!!!!!!! main finished {traceId:79, spanId:80, parentId:0, operationName:"parent"}
?????????? {traceId:79, spanId:81, parentId:80, operationName:"hello"}
?????????? {traceId:79, spanId:82, parentId:80, operationName:"hello"}
?????????? {traceId:79, spanId:83, parentId:80, operationName:"fallback"}
?????????? {traceId:79, spanId:84, parentId:80, operationName:"hello"}
?????????? {traceId:79, spanId:80, parentId:0, operationName:"parent"}
```

What happens here is that in the last retry, the execution times out (remember there's 1 millisecond timeout), which immediately causes yet another retry attempt. That won't happen, because `maxRetries` was exhausted, and so the fallback is executed. And it's only after the fallback finishes when the thread, which was supposed to execute the guarded method from the last retry attempt, actually wakes up and runs the method.

I think this is actually valid. There's no guarantee that when timeout occurs, the execution will not happen. The only guarantee is that the thread is interrupted. Another guarantee is that the `CompletionStage` will be completed exceptionally as soon as timeout is detected, which may be sooner than the executing thread is interrupted (though we should probably interrupt the thread sooner than we complete the `CompletionStage` with a `TimeoutException`). Therefore, subsequent retry attempts, and eventually fallback, may interleave with the execution (which timed out).

This even means that 2 executions may execute concurrently in case the 1st times out and is immediately retried. Again, I think this is probably valid.

To me, this means that #211 is a correct thing to do.

Thoughts, @michalszynkiewicz @rhusar?

**Comment by Ladicek** [comment]
I've reordered some statements slightly (per above), but the inherent nondeterminism remains. Here's another trace from a failing test (see also https://semaphoreci.com/smallrye/smallrye-fault-tolerance/branches/pull-request-212/builds/13):

```
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 7
2020-04-01 10:59:19.213 [main] invoking CompletionStageFallback
2020-04-01 10:59:19.213 [main] invoking CompletionStageRetry
*************************** main retry attempt 0
2020-04-01 10:59:19.213 [main] invoking CompletionStageTimeout
2020-04-01 10:59:19.215 [main] finished CompletionStageTimeout
2020-04-01 10:59:19.215 [main] finished CompletionStageRetry
2020-04-01 10:59:19.215 [main] finished CompletionStageFallback
%%%%%%%%%%%%%%%%%%%%%%%%%%% pool-2-thread-4 timeout from watcher thread
^^^^^^^^^^^^^^^^^^^^^^^^^^^ pool-1-thread-38 running guarded method
!!!!!!!!!!!!!!!!!! pool-1-thread-38 finished {traceId:43, spanId:45, parentId:44, operationName:"hello"}
%%%%%%%%%%%%%%%%%%%%%%%%%%% pool-1-thread-39 timeout completing on original executor
*************************** pool-1-thread-39 retry attempt 1
2020-04-01 10:59:19.218 [pool-1-thread-39] invoking CompletionStageTimeout
2020-04-01 10:59:19.219 [pool-1-thread-39] finished CompletionStageTimeout
^^^^^^^^^^^^^^^^^^^^^^^^^^^ pool-1-thread-40 running guarded method
%%%%%%%%%%%%%%%%%%%%%%%%%%% pool-2-thread-1 timeout from watcher thread
!!!!!!!!!!!!!!!!!! pool-1-thread-40 finished {traceId:43, spanId:46, parentId:44, operationName:"hello"}
%%%%%%%%%%%%%%%%%%%%%%%%%%% pool-1-thread-41 timeout completing on original executor
*************************** pool-1-thread-41 retry attempt 2
2020-04-01 10:59:19.236 [pool-1-thread-41] invoking CompletionStageTimeout
%%%%%%%%%%%%%%%%%%%%%%%%%%% pool-2-thread-5 timeout from watcher thread
2020-04-01 10:59:19.246 [pool-1-thread-41] finished CompletionStageTimeout
%%%%%%%%%%%%%%%%%%%%%%%%%%% pool-1-thread-43 timeout completing on original executor
*************************** pool-1-thread-43 retry attempt 3
$$$$$$$$$$$$$$$$$$$$$$$$$$$ pool-1-thread-43 fallback logic
!!!!!!!!!!!!!!!!!! pool-1-thread-43 finished {traceId:43, spanId:47, parentId:44, operationName:"fallback"}
!!!!!!!!!!!!!!!!!! main finished {traceId:43, spanId:44, parentId:0, operationName:"parent"}
^^^^^^^^^^^^^^^^^^^^^^^^^^^ pool-1-thread-42 running guarded method
!!!!!!!!!!!!!!!!!! pool-1-thread-42 finished {traceId:43, spanId:48, parentId:44, operationName:"hello"}
?????????? {traceId:43, spanId:45, parentId:44, operationName:"hello"}
?????????? {traceId:43, spanId:46, parentId:44, operationName:"hello"}
?????????? {traceId:43, spanId:47, parentId:44, operationName:"fallback"}
?????????? {traceId:43, spanId:44, parentId:0, operationName:"parent"}
?????????? {traceId:43, spanId:48, parentId:44, operationName:"hello"}
```

Same thing that was described in previous analysis happens here, too: the timeout action triggers a retry, which triggers a fallback, which eventually triggers completion of the entire FT chain, but one of the executions that timed out is still running.

I'll update #211 with the reordering and merge it. This one has served its purpose.

**Pull request closed without merging**
