### PR TITLE
add @BeforeRetry

### LINKED ISSUE #259: prototype "before retry action" support
Interesting idea from https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/fault.20tolerance.20using.20.40Retry.20annotation

It would be nice to support running arbitrary user-provided code before each and every retry attempt.

API-wise, it could be another attribute on the already overcrowded `@Retry` annotation, or it could be a CDI event (as those are processed synchronously).

### PR DESCRIPTION
**Pull request by Ladicek**
Fixes #259

### CODE REVIEW

**Comment by Ladicek** [comment]
This is a draft, because tests are missing. Documentation probably also needs some improvement.

Publishing early to solicit feedback from @cescoffier and @geoand. I don't think you need to review everything, just look at the `api` module (especially the `@BeforeRetry` annotation). I'm especially interested in knowing whether these 2 aspects work for you:

- the before retry method is always `void` and has no parameters
- it must not block, it must be short and it must not throw

It would be possible to add parameters, similarly to how `@Fallback` works. It would probably also be possible to make it return `CompletionStage<Void>` (and other async types) so that async work is possible (in addition to `void` if async work is not necessary).

That's probably all.

**Comment by geoand** [comment]
Nice!

I'll have a look soon

**Comment by cescoffier** [comment]
LGTM,

We will likely automatically inject that annotation in Quarkus langchain4j.

**Comment by geoand** [comment]
Lovely, we will certainly make use of it!

**Comment by Ladicek** [comment]
OK, I take it the current API is good for you. I'll merge this and release. If it turns out the API is not sufficient, we can come back to it.

**Pull request merged**
