### PR TITLE
Command listeners are invoked for any FT operation

### LINKED ISSUE #16: Command listeners should be invoked for any FT operation
Currently, they're only invoked for methods annotated with `@Asynchronous`.

### PR DESCRIPTION
**Pull request by mkouba**
- resolves #16

### CODE REVIEW

**Comment by mkouba** [comment]
I'll check the CI failures :-(

**Comment by mkouba** [comment]
I cannot reproduce the issue locally...

**Comment by antoinesd** [comment]
@mkoube I'm afraid you have to rebase after previous merge.

**Comment by mkouba** [comment]
No problem...

**Pull request merged**
