### PR TITLE
 Make implementation more extensible and portable 

### PR DESCRIPTION
**Pull request by mkouba**

### CODE REVIEW

**Comment by mkouba** [comment]
Looks like `maven-javadoc-plugin` settings are too strict...

**Comment by antoinesd** [comment]
@mkouba since `maven-javadoc-plugin` config is inherited from SmallRye parent is it wise to override it in the project ?

**Comment by mkouba** [comment]
Probably not, but it seems it wasn't so strict before, because I can see errors like:
```
[ERROR] /home/runner/smallrye-fault-tolerance/implementation/src/main/java/io/smallrye/faulttolerance/SimpleCommand.java:57: warning: no description for @param
[ERROR]      * @param operation
[ERROR]        ^
```

**Comment by mkouba** [comment]
@antoinesd @kenfinnigan So it passed now ;-)

**Pull request merged**
