### PR TITLE
SmallRye Fault Tolerance 4.0

### PR DESCRIPTION
**Pull request by michalszynkiewicz**

### CODE REVIEW

**Comment by kenfinnigan** [comment]
any idea why it's taking more than an hour to complete?

**Comment by michalszynkiewicz** [comment]
@kenfinnigan I think it hanged, would be great to access the semaphore log but they don't load for me.

**Comment by michalszynkiewicz** [comment]
I suspect it is connected with the failure for the core pool size = 1, I think the core pool should not be queued. I'm testing such setting locally and plan to update this PR shortly if all goes well.

**Comment by michalszynkiewicz** [comment]
a PR showing how to integrate the new version with Quarkus: https://github.com/quarkusio/quarkus/pull/6300/files (passes all the FT related tests)

**Pull request merged**
