### PR TITLE
Upgrade Eclipse MicroProfile Fault Tolerance API to 2.1.1

### PR DESCRIPTION
**Pull request by rhusar**

### CODE REVIEW

**Comment by Ladicek** [comment]
This is something I need to test (both in SmallRye itself and with Quarkus) and, in case of issues, provide feedback in the MP FT community. But this won't be merged as is; we'll only update when final version of 2.1.1 is out.

**Comment by rhusar** [comment]
@Ladicek Yeah that's fine - the intention is to see what CI thinks :-)

**Comment by rhusar** [comment]
Great, looks like CI is happy with this (so does in WildFly).

**Comment by Ladicek** [comment]
Actually I totally forgot to remove that workaround. I think let's keep this PR open and use it later for the real 2.1.1.

**Comment by rhusar** [comment]
@Ladicek Yeah, I will update it immediately as a new release comes out. It will probably be just a retag of this RC.

**Comment by Ladicek** [comment]
Most likely, yea.

**Comment by rhusar** [comment]
RC2 is out!

**Comment by Ladicek** [comment]
Thanks. I tried with RC2 locally earlier today, and also with Quarkus, TCK still passes :-)

**Comment by Ladicek** [comment]
There's an RC3 now.

**Comment by rhusar** [comment]
Right, I was already testing yesterday and it was passing locally. Lets see what CI thinks!

**Comment by rhusar** [comment]
RC4 is out now.

**Comment by rhusar** [comment]
Rebased to trigger new CI runs.

**Comment by Ladicek** [comment]
Thanks. I've heard on the MP FT call yesterday that RC4 seems fine for everyone, so hopefully the final version will be out soon.

**Comment by rhusar** [comment]
Final is out - updated the PR. The CI will probably fail initially since this will take a while to sync to maven repo.

**Comment by Ladicek** [comment]
Yay! Thanks.

FYI, I plan to release 4.2.1 with this chane, and them bump to 4.3.0 and release that with #235.

**Comment by rhusar** [comment]
Sounds good.

**Pull request merged**
