### PR TITLE
release 4.2.1

### PR DESCRIPTION
**Pull request by Ladicek**

### CODE REVIEW

**Comment by Ladicek** [comment]
OK, here we go!

**Comment by Ladicek** [comment]
Hmm, I said I want next to be `4.3.0-SNAPSHOT`, and yet it's `4.2.2-SNAPSHOT`: https://github.com/smallrye/smallrye-fault-tolerance/commit/482dbe4ede0dc23ad53d56bf250335b5ea79baee

@radcortez is that a known issue?

**Comment by radcortez** [comment]
Hum. Weird. Let me check.

**Comment by radcortez** [comment]
Ops. There is a bug in the release script:
https://github.com/smallrye/smallrye-fault-tolerance/blob/fc2918f78450f889b854c6f3272f23835eb5dec7/.github/workflows/release.yml

It's missing the next-version parameter in the release command. I'll send a fix.

**Comment by Ladicek** [comment]
Thank you!

**Pull request merged**
