### PR TITLE
release 4.2.1

### PR DESCRIPTION
**Pull request by Ladicek**

### CODE REVIEW

**Comment by Ladicek** [comment]
Hi @radcortez, is this the right way to trigger the release? Thanks!

**Comment by Ladicek** [comment]
I see this in the "pre release" check:

```
Run radcortez/milestone-review-action@master
Checking Milestone 4.2.1
Found Milestone 4.2.1
Milestone has no issues open.
(node:2991) UnhandledPromiseRejectionWarning: HttpError: Resource not accessible by integration
    at /home/runner/work/_actions/radcortez/milestone-review-action/master/node_modules/@octokit/request/dist-node/index.js:66:23
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:2991) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2991) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Is that OK?

**Comment by rhusar** [comment]
I am seeing these files for the first time. Clearly they came in through https://github.com/smallrye/smallrye-fault-tolerance/commit/fc2918f78450f889b854c6f3272f23835eb5dec7 without any pull request but committed directly to the branch....

**Comment by radcortez** [comment]
Hi @Ladicek 

The file change yes, but the PR needs to come from a a branch in the `origin` repo. The reason for this is that for security reasons, Github doesn't share the secrets required to perform the release to forks.

Can you close this PR and open a new one from a branch in the main repo? After the release is done, you can delete it.

**Comment by radcortez** [comment]
> I am seeing these files for the first time. Clearly they came in through [fc2918f](https://github.com/smallrye/smallrye-fault-tolerance/commit/fc2918f78450f889b854c6f3272f23835eb5dec7) without any pull request but committed directly to the branch....

Yes, it needs to be done that way, or it will trigger the release process :)

**Comment by rhusar** [comment]
@radcortez Hm, that does sound finicky... but hopefully people know what they are doing so we don't have to have more no-changes automated messy releases.

**Comment by Ladicek** [comment]
Ah, gotcha. Easiest to do it from GitHub web UI I guess :-)

**Comment by radcortez** [comment]
> @radcortez Hm, that does sound finicky... but hopefully people know what they are doing so we don't have to have more no-changes automated messy releases.

No worries, nothing will happen unless it gets approved. Now, the GH Action does have that little inconvenience. Since it monitors the `project.yml` file, it doesn't distinguish when you are adding the file for the first time :)

From now on, it should be fine.

**Pull request closed without merging**
